/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAmenitiesRouteImport } from './routes/_authenticated/amenities'
import { Route as AuthenticatedAreasRouteImport } from './routes/_authenticated/areas'
import { Route as AuthenticatedBannersRouteImport } from './routes/_authenticated/banners'
import { Route as AuthenticatedBlogsRouteImport } from './routes/_authenticated/blogs'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedCitiesRouteImport } from './routes/_authenticated/cities'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedRedirectsRouteImport } from './routes/_authenticated/redirects'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedSeoRouteImport } from './routes/_authenticated/seo'
import { Route as AuthenticatedSitemapRouteImport } from './routes/_authenticated/sitemap'
import { Route as AuthenticatedTestimonialsRouteImport } from './routes/_authenticated/testimonials'
import { Route as AuthenticatedPagesIndexRouteImport } from './routes/_authenticated/pages.index'
import { Route as AuthenticatedPagesHomeRouteImport } from './routes/_authenticated/pages.home'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties.index'
import { Route as AuthenticatedPropertiesExpiredRouteImport } from './routes/_authenticated/properties.expired'
import { Route as AuthenticatedPropertiesFeaturedRouteImport } from './routes/_authenticated/properties.featured'
import { Route as AuthenticatedPropertiesNewRouteImport } from './routes/_authenticated/properties.new'
import { Route as AuthenticatedPropertiesPendingRouteImport } from './routes/_authenticated/properties.pending'
import { Route as AuthenticatedSettingsAdminsRouteImport } from './routes/_authenticated/settings.admins'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings.general'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings.roles'
import { Route as AuthenticatedSettingsSystemRouteImport } from './routes/_authenticated/settings.system'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAmenitiesRoute = AuthenticatedAmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAreasRoute = AuthenticatedAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBannersRoute = AuthenticatedBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBlogsRoute = AuthenticatedBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCitiesRoute = AuthenticatedCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRedirectsRoute = AuthenticatedRedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSeoRoute = AuthenticatedSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSitemapRoute = AuthenticatedSitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTestimonialsRoute =
  AuthenticatedTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPagesIndexRoute = AuthenticatedPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPagesHomeRoute = AuthenticatedPagesHomeRouteImport.update({
  id: '/pages/home',
  path: '/pages/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesExpiredRoute =
  AuthenticatedPropertiesExpiredRouteImport.update({
    id: '/properties/expired',
    path: '/properties/expired',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesFeaturedRoute =
  AuthenticatedPropertiesFeaturedRouteImport.update({
    id: '/properties/featured',
    path: '/properties/featured',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesNewRoute =
  AuthenticatedPropertiesNewRouteImport.update({
    id: '/properties/new',
    path: '/properties/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesPendingRoute =
  AuthenticatedPropertiesPendingRouteImport.update({
    id: '/properties/pending',
    path: '/properties/pending',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAdminsRoute =
  AuthenticatedSettingsAdminsRouteImport.update({
    id: '/settings/admins',
    path: '/settings/admins',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSystemRoute =
  AuthenticatedSettingsSystemRouteImport.update({
    id: '/settings/system',
    path: '/settings/system',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/amenities': typeof AuthenticatedAmenitiesRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/banners': typeof AuthenticatedBannersRoute
  '/blogs': typeof AuthenticatedBlogsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/cities': typeof AuthenticatedCitiesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/media': typeof AuthenticatedMediaRoute
  '/redirects': typeof AuthenticatedRedirectsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/seo': typeof AuthenticatedSeoRoute
  '/sitemap': typeof AuthenticatedSitemapRoute
  '/testimonials': typeof AuthenticatedTestimonialsRoute
  '/pages/home': typeof AuthenticatedPagesHomeRoute
  '/properties/expired': typeof AuthenticatedPropertiesExpiredRoute
  '/properties/featured': typeof AuthenticatedPropertiesFeaturedRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/properties/pending': typeof AuthenticatedPropertiesPendingRoute
  '/settings/admins': typeof AuthenticatedSettingsAdminsRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/pages/': typeof AuthenticatedPagesIndexRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/amenities': typeof AuthenticatedAmenitiesRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/banners': typeof AuthenticatedBannersRoute
  '/blogs': typeof AuthenticatedBlogsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/cities': typeof AuthenticatedCitiesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/media': typeof AuthenticatedMediaRoute
  '/redirects': typeof AuthenticatedRedirectsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/seo': typeof AuthenticatedSeoRoute
  '/sitemap': typeof AuthenticatedSitemapRoute
  '/testimonials': typeof AuthenticatedTestimonialsRoute
  '/pages/home': typeof AuthenticatedPagesHomeRoute
  '/properties/expired': typeof AuthenticatedPropertiesExpiredRoute
  '/properties/featured': typeof AuthenticatedPropertiesFeaturedRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/properties/pending': typeof AuthenticatedPropertiesPendingRoute
  '/settings/admins': typeof AuthenticatedSettingsAdminsRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/pages': typeof AuthenticatedPagesIndexRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/amenities': typeof AuthenticatedAmenitiesRoute
  '/_authenticated/areas': typeof AuthenticatedAreasRoute
  '/_authenticated/banners': typeof AuthenticatedBannersRoute
  '/_authenticated/blogs': typeof AuthenticatedBlogsRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/cities': typeof AuthenticatedCitiesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/redirects': typeof AuthenticatedRedirectsRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/seo': typeof AuthenticatedSeoRoute
  '/_authenticated/sitemap': typeof AuthenticatedSitemapRoute
  '/_authenticated/testimonials': typeof AuthenticatedTestimonialsRoute
  '/_authenticated/pages/home': typeof AuthenticatedPagesHomeRoute
  '/_authenticated/properties/expired': typeof AuthenticatedPropertiesExpiredRoute
  '/_authenticated/properties/featured': typeof AuthenticatedPropertiesFeaturedRoute
  '/_authenticated/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/_authenticated/properties/pending': typeof AuthenticatedPropertiesPendingRoute
  '/_authenticated/settings/admins': typeof AuthenticatedSettingsAdminsRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/_authenticated/pages/': typeof AuthenticatedPagesIndexRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/amenities'
    | '/areas'
    | '/banners'
    | '/blogs'
    | '/categories'
    | '/cities'
    | '/dashboard'
    | '/media'
    | '/redirects'
    | '/rooms'
    | '/seo'
    | '/sitemap'
    | '/testimonials'
    | '/pages/home'
    | '/properties/expired'
    | '/properties/featured'
    | '/properties/new'
    | '/properties/pending'
    | '/settings/admins'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/system'
    | '/pages/'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/amenities'
    | '/areas'
    | '/banners'
    | '/blogs'
    | '/categories'
    | '/cities'
    | '/dashboard'
    | '/media'
    | '/redirects'
    | '/rooms'
    | '/seo'
    | '/sitemap'
    | '/testimonials'
    | '/pages/home'
    | '/properties/expired'
    | '/properties/featured'
    | '/properties/new'
    | '/properties/pending'
    | '/settings/admins'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/system'
    | '/pages'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/amenities'
    | '/_authenticated/areas'
    | '/_authenticated/banners'
    | '/_authenticated/blogs'
    | '/_authenticated/categories'
    | '/_authenticated/cities'
    | '/_authenticated/dashboard'
    | '/_authenticated/media'
    | '/_authenticated/redirects'
    | '/_authenticated/rooms'
    | '/_authenticated/seo'
    | '/_authenticated/sitemap'
    | '/_authenticated/testimonials'
    | '/_authenticated/pages/home'
    | '/_authenticated/properties/expired'
    | '/_authenticated/properties/featured'
    | '/_authenticated/properties/new'
    | '/_authenticated/properties/pending'
    | '/_authenticated/settings/admins'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/system'
    | '/_authenticated/pages/'
    | '/_authenticated/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/amenities': {
      id: '/_authenticated/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AuthenticatedAmenitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/areas': {
      id: '/_authenticated/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AuthenticatedAreasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/banners': {
      id: '/_authenticated/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof AuthenticatedBannersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blogs': {
      id: '/_authenticated/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof AuthenticatedBlogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cities': {
      id: '/_authenticated/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof AuthenticatedCitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/redirects': {
      id: '/_authenticated/redirects'
      path: '/redirects'
      fullPath: '/redirects'
      preLoaderRoute: typeof AuthenticatedRedirectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seo': {
      id: '/_authenticated/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof AuthenticatedSeoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sitemap': {
      id: '/_authenticated/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof AuthenticatedSitemapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/testimonials': {
      id: '/_authenticated/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof AuthenticatedTestimonialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pages/': {
      id: '/_authenticated/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof AuthenticatedPagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pages/home': {
      id: '/_authenticated/pages/home'
      path: '/pages/home'
      fullPath: '/pages/home'
      preLoaderRoute: typeof AuthenticatedPagesHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/expired': {
      id: '/_authenticated/properties/expired'
      path: '/properties/expired'
      fullPath: '/properties/expired'
      preLoaderRoute: typeof AuthenticatedPropertiesExpiredRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/featured': {
      id: '/_authenticated/properties/featured'
      path: '/properties/featured'
      fullPath: '/properties/featured'
      preLoaderRoute: typeof AuthenticatedPropertiesFeaturedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/new': {
      id: '/_authenticated/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthenticatedPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/pending': {
      id: '/_authenticated/properties/pending'
      path: '/properties/pending'
      fullPath: '/properties/pending'
      preLoaderRoute: typeof AuthenticatedPropertiesPendingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/admins': {
      id: '/_authenticated/settings/admins'
      path: '/settings/admins'
      fullPath: '/settings/admins'
      preLoaderRoute: typeof AuthenticatedSettingsAdminsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/system': {
      id: '/_authenticated/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthenticatedSettingsSystemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAmenitiesRoute: typeof AuthenticatedAmenitiesRoute
  AuthenticatedAreasRoute: typeof AuthenticatedAreasRoute
  AuthenticatedBannersRoute: typeof AuthenticatedBannersRoute
  AuthenticatedBlogsRoute: typeof AuthenticatedBlogsRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedCitiesRoute: typeof AuthenticatedCitiesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedRedirectsRoute: typeof AuthenticatedRedirectsRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedSeoRoute: typeof AuthenticatedSeoRoute
  AuthenticatedSitemapRoute: typeof AuthenticatedSitemapRoute
  AuthenticatedTestimonialsRoute: typeof AuthenticatedTestimonialsRoute
  AuthenticatedPagesHomeRoute: typeof AuthenticatedPagesHomeRoute
  AuthenticatedPropertiesExpiredRoute: typeof AuthenticatedPropertiesExpiredRoute
  AuthenticatedPropertiesFeaturedRoute: typeof AuthenticatedPropertiesFeaturedRoute
  AuthenticatedPropertiesNewRoute: typeof AuthenticatedPropertiesNewRoute
  AuthenticatedPropertiesPendingRoute: typeof AuthenticatedPropertiesPendingRoute
  AuthenticatedSettingsAdminsRoute: typeof AuthenticatedSettingsAdminsRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsSystemRoute: typeof AuthenticatedSettingsSystemRoute
  AuthenticatedPagesIndexRoute: typeof AuthenticatedPagesIndexRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAmenitiesRoute: AuthenticatedAmenitiesRoute,
  AuthenticatedAreasRoute: AuthenticatedAreasRoute,
  AuthenticatedBannersRoute: AuthenticatedBannersRoute,
  AuthenticatedBlogsRoute: AuthenticatedBlogsRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedCitiesRoute: AuthenticatedCitiesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedRedirectsRoute: AuthenticatedRedirectsRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedSeoRoute: AuthenticatedSeoRoute,
  AuthenticatedSitemapRoute: AuthenticatedSitemapRoute,
  AuthenticatedTestimonialsRoute: AuthenticatedTestimonialsRoute,
  AuthenticatedPagesHomeRoute: AuthenticatedPagesHomeRoute,
  AuthenticatedPropertiesExpiredRoute: AuthenticatedPropertiesExpiredRoute,
  AuthenticatedPropertiesFeaturedRoute: AuthenticatedPropertiesFeaturedRoute,
  AuthenticatedPropertiesNewRoute: AuthenticatedPropertiesNewRoute,
  AuthenticatedPropertiesPendingRoute: AuthenticatedPropertiesPendingRoute,
  AuthenticatedSettingsAdminsRoute: AuthenticatedSettingsAdminsRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedSettingsSystemRoute: AuthenticatedSettingsSystemRoute,
  AuthenticatedPagesIndexRoute: AuthenticatedPagesIndexRoute,
  AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
